# fly.toml app configuration file generated for cartesi-coprocessor-solver-dev on 2025-01-02T13:27:05+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'cartesi-coprocessor-solver-dev'
primary_region = 'jnb'

[build]

[http_service]
  internal_port = 3033
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 2
